# Stage 1: Build the Go binary
FROM golang:alpine AS builder

# Set the working directory inside the container
WORKDIR /hello-microservice

# Copy the entire project
COPY ../.. /hello-microservice

# Change to the service directory to access go.mod and build the binary
# CGO_ENABLED=0 and GOOS=linux are for creating a static binary that can run in a minimal container
RUN cd services/hello-service && CGO_ENABLED=0 GOOS=linux go build -o /hello-service .

# Stage 2: Create the final minimal image
FROM alpine:latest

# Copy the built binary from the builder stage
COPY --from=builder /hello-service /hello-service

# Expose the port the gateway service runs on
EXPOSE 50051

# Command to run the executable
CMD ["/hello-service"]